# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: 'macos-14'

    strategy:
      fail-fast: false
      matrix:
        # Escape spaces and parentheses in the device string
        device:
          - "'iPhone SE (3rd generation)'"
          - "'iPhone 15 Pro Max'"
          - "'iPad Pro (11-inch) (4th generation)'"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: bundle install

      - name: Install xcbeautify, xcodes, and xcodegen
        run: |
          brew install xcbeautify
          brew install xcodesorg/made/xcodes
          brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Run Tests
        run: bundle exec fastlane ios test device:${{ matrix.device }}
